# Generated by Django 2.0.5 on 2018-08-13 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('resources', '0002_auto_20180809_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerControl',
            fields=[
                ('user', models.OneToOneField(on_delete='', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
