# Generated by Django 2.0.5 on 2018-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_managercontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(on_delete='', to='resources.Manufacturer', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa'),
        ),
    ]
